services:
  todo-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - todo-volume:/var/lib/postgresql/data

  api:
    image: lugchy/todo-api:latest
    ports:
      - "8000:8000"
    depends_on:
      - todo-db
    env_file:
      - .env 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: todo-db 
      DB_PORT: ${DB_PORT}
    command: ./start.sh
    
volumes:
  todo-volume:
